name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: t10&#45;01&#45;01
      id: t10-45-01-45-01
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: t10&#45;01&#45;01
        setup-command: make compile
        command: make -s test_01
        input: |
          dorm-print-all-detail
          student-print-all-detail
          ---
        expected-output: |
          Antiokia|5|male|0
          Mamre|5|male|0
          Silo|5|male|0
          Mahanaim|5|male|0
          Nazaret|5|male|0
          12S21001|Dhino Turnip|2021|male|unassigned
          12S21002|Marudut Tampubolon|2021|male|unassigned
          12S21003|Jusas Tampubolon|2021|male|unassigned
          12S21004|Estomihi pangaribuan|2021|male|unassigned
          12S21006|Weny Sitinjak|2021|female|unassigned
        comparison-method: exact
        timeout: 1
        max-score: 20
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        T10-45-01-45-01_RESULTS: "${{steps.t10-45-01-45-01.outputs.result}}"
      with:
        runners: t10-45-01-45-01
